### PR TITLE
teams/tidb: a vote for mornyx as tidb reviewer

### PR DESCRIPTION
**Pull request by breeswish**
@mornyx has been [working for](https://github.com/pingcap/tidb/pulls?q=is%3Apr+author%3Amornyx+is%3Aclosed) the Top SQL feature of TiDB for several months, revealed sufficient capability.

### CODE REVIEW

**Review by qw4990 — APPROVED** [review]
LGTM

**Review by crazycs520 — APPROVED** [review]

**Comment by bb7133** [comment]
LGTM

**Review by tangenta — APPROVED** [review]

**Comment by zhangyangyu** [comment]
[CLA assistant check](http://152.32.212.5:5000/pingcap/community?pullRequest=655) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](http://152.32.212.5:5000/pingcap/community?pullRequest=655) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](http://152.32.212.5:5000/check/pingcap/community?pullRequest=655) it.</sub>

**Pull request merged**
