### PR TITLE
.gitignore: add ".idea"

### PR DESCRIPTION
**Pull request by wolfstudy**
Signed-off-by: xiaolong.ran <rxl@apache.org>

## Modifications

- Add `.idea` to `.gitignore` file

### CODE REVIEW

**Comment by zz-jason** [comment]
> In here, I only added .idea, maybe we can add more files to `.gitignore`.
> 
> we can provide an issue template and pull request template, this makes it easier to get the information we want from the contributors

Sure, it would be nice to have them all! BTW, I think we can merge this PR first. Would you mind to help us finish these template files?

**Comment by gingerkidney** [comment]
@wolfstudy please sign the CLA

**Comment by wolfstudy** [comment]
> BTW, I think we can merge this PR first. Would you mind to help us finish these template files?

Sure, glad to help.

**Comment by wolfstudy** [comment]
> @wolfstudy please sign the CLA

Sorry, I missed the message. done, please check.


image

**Comment by wolfstudy** [comment]
ping @zz-jason PTAL thanks.

**Pull request merged**
