### PR TITLE
sig-planner: add reviewers

### PR DESCRIPTION
**Pull request by winoros**
Promote three reviewer
Both of them contributes many codes for planner-sig.
And designed thing such as new statistics for sampling based data, and the index usage table.

### CODE REVIEW

**Comment by qw4990** [comment]
LGTM

**Comment by qw4990** [comment]
PTAL @zz-jason

**Comment by hi-rustin** [comment]
> LGTM

`LGTM `command can not work for new bot.

Please refer to https://book.prow.tidb.io/plugins/lgtm.html and use `/LGTM`. Thanks!

**Comment by qw4990** [comment]
LGTM

**Review by lzmhhh123 — APPROVED** [review]
LGTM

**Comment by winoros** [comment]
@hi-rustin How to merge it? thx

**Comment by hi-rustin** [comment]
> @hi-rustin How to merge it? thx

Please refer to https://book.prow.tidb.io/plugins/merge.html.

**Pull request merged**
