### PR TITLE
Revert "teams/migration: vote for okJiang as migration reviewer"

### PR DESCRIPTION
**Pull request by lance6716**
Reverts pingcap/community#555

violate governance rule

### CODE REVIEW

**Comment by lance6716** [comment]
sorry for my action, maybe we should add a CI of opening days? @tisonkun

**Comment by tisonkun** [comment]
@lance6716 we have [23 tidb maintainers](https://github.com/orgs/pingcap/teams/tidb-maintainers). It is not a big number. If we don't have consensus even in this group, it is _not_ a community. Community bridges _people_, not creates rules. We aren't in a cyberpunk era 😄

**Review by kennytm — APPROVED** [review]

**Comment by kennytm** [comment]
@tisonkun 

1. the rules already existed in https://github.com/pingcap/community/tree/master/teams#decision-making
2. i don't see how having a bot to verify if the PR is open for at least 3 days is considered "cyberpunk". the same bot already checked for the `status/can-merge` label right here right now.
3. heck we in Rust are using [rfcbot](https://github.com/rust-lang/rfcbot-rs#rfcbot) to count votes and keep a decision open for final-comment-period and no one complained that introducing rfcbot burned the community bridge.

**Comment by tisonkun** [comment]
@kennytm thanks for your reply. With the original, maybe we can revert it (by merging this PR) and redo the action.

> the rules already existed in https://github.com/pingcap/community/tree/master/teams#decision-making

Yes. A maintainer should know why vote and how to vote before applying their power. Also, it is a dedicated section in the content talking about the deadline. A review should notice it.

> i don't see how having a bot to verify if the PR is open for at least 3 days is considered "cyberpunk". the same bot already checked for the status/can-merge label right here right now.

It may seem simple to add some rules at the beginning, but end with time after time new requirements. We use bot for automations, not AI. Even we require 2 LGTM from the proposed team, the bot only counts 1 LGTM from anyone with write permission. We can hardly maintain so many rules within a bot.

If you have a solution that cause less regression/complain later, I'm TOTALLY willing to learn from it. I don't know if we can just use rfcbot. It seems we don't have man-force to develop and maintain such one new - we have more than three bots historically, none of them are full featured as wish.

**Comment by kennytm** [comment]
> Yes. A maintainer should know why vote and how to vote before applying their power. Also, it is a dedicated section in the content talking about the deadline. A reviewer should notice it.

Technically the problem from #555 isn't voting. The `/merge` acts as the final approval, and unfortunately reverting it is very expensive for now, unlike the votes.

> It may seem simple to add some rules at the beginning, but end with time after time new requirements. 

I think new decision making methods require consensus from maintainers. If even a bot can't handle this perhaps that decision method shouldn't be adopted at all 😂. Adding a simple rule at the beginning doesn't mean we have to support more complex rules, that's slippery slope argument. Plus a human can always override the bot decision by clicking the "Squash and merge" button 🙃.

> If you have a solution that cause less regression/complain later, I'm TOTALLY willing to learn from it.

I'd suggest starting simple with what we already have.

1. create 6 [pull request templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) for the 6 actions (or "issue templates" if we want to make it a two-step process)
2. introduce 5 labels: **`do-not-merge/pending-consensus`**, **`do-not-merge/pending-lazy-majority`**, **`do-not-merge/pending-2/3-majority`**, **`do-not-merge/3-day-consultation`**, **`do-not-merge/6-day-consultation`** which are automatically applied based on which action chosen (not sure if PR template supports this)
3. Disallow `/merge` when at least one of these labels is present. Maintainers can remove these labels after verification. Since these labels don't appear in other TiDB repos this should reduce the chance people unknowingly sending `/merge` after seeing LGT2.
    * if possible, make the bot repeat the rules when these labels are present, like

        ```
        This PR cannot be merged yet, because:
         * it is waiting for consensus (two binding +1 votes and no -1 vetoes)
        
        You can remove the `do-not-merge/pending-consensus` label if the conditions are already satisfied, and issue `/merge` again.
        ```

        ```
        This PR cannot be merged yet, because:
         * it should be open for >3 days

        You can remove the `do-not-merge/3-day-consultation` label if the conditions are already satisfied, and issue `/merge` again.
        ```

4. in the future, the bot can automatically can the condition and remove those labels.

**Comment by tisonkun** [comment]
@kennytm thanks for your suggestion! I think we can keep the process as is for a while to get more inputs.

For the bot part, I don't see a clear path now to achieve it with @ti-chi-bot . @Mini256 the maintainer may have richer knowledge on the technical part. We can continue a bit the discussion here and if it goes into the tech part, file an issue at the bot repo.

**Pull request merged**
