### PR TITLE
promote zimulala to sig/exec committer

### PR DESCRIPTION
**Pull request by XuHuaiyu**
close https://github.com/pingcap/community/issues/427

### CODE REVIEW

**Review by wshwsh12 — APPROVED** [review]

**Comment by hi-rustin** [comment]
/close 

Please follow the [new promotion process](https://docs.google.com/document/d/1OvlpU00W_LpTL09zB3gvDyQzHULz27kmNKH2O0seWCI/edit).

For example: https://github.com/pingcap/community/issues/414

If you have any questions please feel free to @ me.

**Comment by zimulala** [comment]
@hi-rustin 
I added #426

**Comment by hi-rustin** [comment]
/reopen

/lgtm

/merge

Thank you all.

**Pull request merged**
