### PR TITLE
teams/tidb: a vote for lcwangchao as the committer

### PR DESCRIPTION
**Pull request by lcwangchao**
As stated in the title.

### CODE REVIEW

**Comment by bb7133** [comment]
LGTM, I think @lcwangchao shows great understandings on 'ddl' and 'txn' components of TiDB from his previous work.

**Comment by bb7133** [comment]
Keep this PR open for at least 6 days:

> The vote will be open for at least 6 days unless there is an objection or not enough votes.

**Comment by tisonkun** [comment]
@lcwangchao could you communicate with a tidb team maintainer to moderate the nomination?

Almost we ask maintainers to nominate new members in [Roles and Responsibility](https://github.com/pingcap/community/tree/master/teams#roles-and-responsibilities).

> Maintainers should nominate new reviewer, committers and maintainers, and should also strive to only nominate new candidates outside of their own organization.

The rationale here is that open the gate to everyone nominates anybody make the governance quite ambiguous. Nominate somebody as a new member is a high trust level, it means the nominator is supposed to have well knowledge on the community principle, and how to act in the community, so that he/she can decide whether or not the nominee is well fit in the community culture and works well.

Also, community grows with trust spread, someone should endorse your contribution, so why not a maintainer create and moderate the nomination?

You may argue that @bb7133 has already sent his approval above and we let it happen. But it is 4 hours later. Shall we create a rule to wait for 4 hours for anybody nominating himself/herself? I don't think so.

**Comment by lcwangchao** [comment]
> @lcwangchao could you communicate with a tidb team maintainer to moderate the nomination?
> 
> Almost we ask maintainers to nominate new members in [Roles and Responsibility](https://github.com/pingcap/community/tree/master/teams#roles-and-responsibilities).
> 
> > Maintainers should nominate new reviewer, committers and maintainers, and should also strive to only nominate new candidates outside of their own organization.
> 
> ... also
> 
> > Review access is by invitation only and must be approved by consensus of the maintainers.
> > Commit access is by invitation only and must be approved by consensus of the maintainers.
> > Membership of the maintainers is by invitation only and must be approved by a consensus of the maintainers.
> 
> The rationale here is that open the gate to everyone nominates anybody make the governance quite ambiguous. Nominate somebody as a new member is a high trust level, it means the nominator is supposed to have well knowledge on the community principle, and how to act in the community, so that he/she can decide whether or not the nominee is well fit in the community culture and works well.
> 
> Also, community grows with trust spread, someone should endorse your contribution, so why not a maintainer create and moderate the nomination?
> 
> You may argue that @bb7133 has already sent his approval above and we let it happen. But it is 4 hours later. Shall we create a rule to wait for 4 hours for anybody nominating himself/herself? I don't think so.

OK，I'll close this PR and then communicate with a tidb team maintainer.

**Comment by tisonkun** [comment]
@lcwangchao thank you for your understanding!

**Pull request closed without merging**
