### PR TITLE
teams/tidb: a vote for ChenPeng2013 as the reviewer

### PR DESCRIPTION
**Pull request by bb7133**
As stated in the title.

### CODE REVIEW

**Comment by tisonkun** [comment]
/cc @pingcap/tidb-maintainers 

With an offline discussion with @bb7133 , we're still exploring the principle to accept contribution beyond code. It's better to listen to opinions from our maintainers.

I'll prepare a draft of committer principle later.

**Comment by zhangyangyu** [comment]
> Is the TiDB 'reviewer' role just a kind of honor? or is it for someone who would help us to review the code and ease the burden of other developers? 

I think usually both are. The roles serves as a kind of honor and gives the qualified contributors right to do more work, which certainly means more obligation. The roles shall not mean simplified workflow. Everyone in the community follows the same workflow. But there are various kinds of contributions in the community, even under the GitHub PingCAP repos, not every one directly contributing to the tidb repo. We only have three roles: reviewer, committer, maintainer. Of course we can have more but I don't think that's necessary. Extending the current roles to a wider scope of contributions is okay. Then under the same role, how do we ensure the quality of community actions? My answer is by other people. If a person keeps contributing harmful PRs, reviews, or if a person contributing something harmful beyond his/her scope, will other people takes his/her contribution serious? From my experience, people in the community behaves really good usually and the worst case usually don't happen. We don't have to bring much complex at early stage. But what if the worst case happen? We should turn to the CoC and take him/her out.

**Comment by zhangyangyu** [comment]
ping @pingcap/tidb-maintainers how do you think about this vote? You need to +1 or -1. If there are still concerns about standards granting roles, you could -1 for this vote and let's have more discussion on forum.

**Comment by sunxiaoguang** [comment]
> > Is the TiDB 'reviewer' role just a kind of honor? or is it for someone who would help us to review the code and ease the burden of other developers?
> 
> I think usually both are. The roles serves as a kind of honor and gives the qualified contributors right to do more work, which certainly means more obligation. The roles shall not mean simplified workflow. Everyone in the community follows the same workflow. But there are various kinds of contributions in the community, even under the GitHub PingCAP repos, not every one directly contributing to the tidb repo. We only have three roles: reviewer, committer, maintainer. Of course we can have more but I don't think that's necessary. Extending the current roles to a wider scope of contributions is okay. Then under the same role, how do we ensure the quality of community actions? My answer is by other people. If a person keeps contributing harmful PRs, reviews, or if a person contributing something harmful beyond his/her scope, will other people takes his/her contribution serious? From my experience, people in the community behaves really good usually and the worst case usually don't happen. We don't have to bring much complex at early stage. But what if the worst case happen? We should turn to the CoC and take him/her out.

+1

**Review by tiancaiamao — APPROVED** [review]

**Comment by tiancaiamao** [comment]
OK, I think it's acceptable as long as a reviewer take this honor, and never do something harmful to the repo (at the risk of a stain on the reputation of himself)

**Comment by sunxiaoguang** [comment]
> OK, I think it's acceptable as long as a reviewer take this honor, and never do something harmful to the repo (at the risk of a stain on the reputation of himself)

Yes, the membership of each role can be revoked by a consensus of the maintainers.

**Review by disksing — APPROVED** [review]

**Comment by sunxiaoguang** [comment]
vote will last for 6 days before this PR can be merged.

**Comment by sunxiaoguang** [comment]
Thanks for your contribution @ChenPeng2013
Congrats

**Pull request merged**
