### PR TITLE
Propose @howardlau1999 as reviewer of sig-k8s

### PR DESCRIPTION
**Pull request by Yisaer**
Signed-off-by: Song Gao <disxiaofei@163.com>

1. He filed more than 15+ PR
2. He implemented the autoscaling including CRD design / controller logic / unit-test / e2e test which is a hard and large task, and he did it quite well.

### CODE REVIEW

**Review by rleungx — APPROVED** [review]
@howardlau1999 Congrats!

**Review by DanielZhangQD — APPROVED** [review]
LGTM

**Review by lonng — APPROVED** [review]
LGTM

**Review by winkyao — APPROVED** [review]

**Pull request merged**
