### PR TITLE
README.md: delete tidb-roadmap in README.md

### LINKED ISSUE #549: The link of roadmap is not accessible.
As described in the title, PTAL.

https://github.com/pingcap/community#tidb-roadmap

### PR DESCRIPTION
**Pull request by Defined2014**
close #549, delete tidb-roadmap

### CODE REVIEW

**Comment by Defined2014** [comment]
/cc @tisonkun 
PTAL

**Comment by Defined2014** [comment]
/cc @winkyao 
PTAL

**Review by tisonkun — APPROVED** [review]
LGTM

**Comment by tisonkun** [comment]
@Defined2014 thanks for your contribution!

**Pull request merged**
