### PR TITLE
teams/docs: a vote for shichun-0415 as the reviewer

### PR DESCRIPTION
**Pull request by TomShawn**
As stated in the title.

Hi @pingcap/tidb-maintainers, PTAL.

/hold

### CODE REVIEW

**Review by hfxsd — APPROVED** [review]
LGTM

**Review by qiancai — APPROVED** [review]

**Review by lilin90 — APPROVED** [review]
LGTM

**Comment by sunxiaoguang** [comment]
Thanks for your contribution! @shichun-0415 Congrats.

**Pull request merged**
