### PR TITLE
Rename sig-ddl to sig-sql-infra

### PR DESCRIPTION
**Pull request by tangenta**
After the disscusion and voting about [the new name of SIG-DDL](https://docs.google.com/document/d/1RNIS_9Yl2VLXP5aK0KW6nEoHvp5UIoHI1TnnlyyClZQ/edit#), finally we decided to use "sig-sql-infra" as the new name of sig-ddl.

This PR update the information related to sig-ddl.

### CODE REVIEW

**Comment by hi-rustin** [comment]
/hold

Waiting more work.

**Comment by hi-rustin** [comment]
TODO(hi-rustin):

- [ ] update sig name
- [ ] update sig channel link
- [ ] update sig link for web site
- [ ] update sig label for all repos(sql-infra team)

**Comment by hi-rustin** [comment]
/cc @pingcap/tidb-maintainer 

PTAL~  After you approve to these changes, I will continue to do some data updates.

**Comment by hi-rustin** [comment]
@pingcap/tidb-maintainer  ping~

**Review by jackysp — COMMENTED** [review]
/lgtm

**Pull request merged**
