### PR TITLE
Promote xiongjiwei as the committer for DDL sig

### PR DESCRIPTION
**Pull request by wjhuang2016**
Since @xiongjiwei  has contributed a lot to sig-ddl, according to sig-ddl [roles-and-organization-management.md](https://github.com/pingcap/community/blob/master/special-interest-groups/sig-ddl/roles-and-organization-management.md#promotion), we would like to promote him to our new committer, and his detailed contribution is shown below:

1.  Contribute [20+](https://github.com/pingcap/tidb/pulls?q=is%3Apr+label%3Asig%2FDDL+author%3Axiongjiwei+is%3Aclosed) PRs to the DDL sig.
2. Review [10+](https://github.com/pingcap/tidb/pulls?q=is%3Apr+reviewed-by%3Axiongjiwei+-author%3Axiongjiwei) PRs.
3. Implement unicode-ci in both TiDB and TiKV.

### CODE REVIEW

**Comment by bb7133** [comment]
LGTM

**Comment by jackysp** [comment]
Please resolve conflicts, @wjhuang2016 .

**Comment by hi-rustin** [comment]
/assign @winkyao

/assign @zz-jason

Needs /merge.

**Pull request merged**
