### PR TITLE
teams/tidb: a vote for Defined2014 as reviewer

### PR DESCRIPTION
**Pull request by tiancaiamao**
As stated in the title.

### CODE REVIEW

**Comment by wjhuang2016** [comment]
+1

**Review by zimulala — COMMENTED** [review]
Do we need to update teams/tidb/membership.json?

**Comment by bb7133** [comment]
+1, please address the comments from @zimulala

**Comment by tiancaiamao** [comment]
> Do we need to update teams/tidb/membership.json?

Done

**Comment by sunxiaoguang** [comment]
Thanks for your contribution. @Defined2014 Congrats

**Review by sunxiaoguang — APPROVED** [review]

**Pull request merged**
