### PR TITLE
sig-migrate: add learning materials and link to issues

### PR DESCRIPTION
**Pull request by kennytm**
Follow up of #366.

### CODE REVIEW

**Comment by kennytm** [comment]
hey the labeller doesn't work

**Comment by kennytm** [comment]
PTAL @lance6716 @amyangfei. if you don't have more learning materials, we can remove the "do-not-merge" label.

**Comment by lance6716** [comment]
DM doesn't have other learning materials and has added "good first issue" label

**Review by lichunzhu — APPROVED** [review]
LGTM

**Comment by glorv** [comment]
LGTM

**Comment by 3pointer** [comment]
LGTM

**Pull request merged**
