### PR TITLE
Add ngaut to maintainer list

### PR DESCRIPTION
**Pull request by ngaut**

### CODE REVIEW

**Comment by bb7133** [comment]
Hi @ngaut , accoridng to the current [roles and responsibility of the community]) https://github.com/pingcap/community/tree/master/teams#actions:

> When a new maintainer is proposed for the team, should be only nominated by a maintainer.

So I would suggest the current maintainer of doc team make the proposal.

PTAL @lilin90 @TomShawn @qiancai @yikeke .

**Review by lilin90 — APPROVED** [review]
LGTM

**Comment by sunxiaoguang** [comment]
I suggest put ngaut to committer, as maintainer takes different responsibility. Committer role is for making contribution or committing other people's contribution.

**Review by TomShawn — APPROVED** [review]
LGTM

**Comment by lilin90** [comment]
In Nov 2021, the Docs Team added [Docs Team Management](https://github.com/pingcap/community/blob/master/teams/docs/docs-team-management.md) as a reference guideline for membership promotion. After secondary consideration, I would close this PR and create another PR to promote @ngaut in Docs Team.

**Comment by lilin90** [comment]
See https://github.com/pingcap/community/pull/615.

**Pull request closed without merging**
