### PR TITLE
sig-exec: promote mmyj to committer

### PR DESCRIPTION
**Pull request by qw4990**
According to [sig-exec roles-and-organization-management.md#promotion](https://github.com/pingcap/community/blob/master/special-interest-groups/sig-exec/roles-and-organization-management.md#promotion), we would like to promote @mmyj to our new committer, his detailed contribution is:
1. contributed [40+ PRs](https://github.com/pingcap/tidb/pulls/mmyj) to the executor,
2. finished the medium task that [recording checksums for spilled files in the disk](https://github.com/pingcap/tidb/issues/16532),
3. finished the medium task that [encrypting for spilled files in the disk](https://github.com/pingcap/tidb/issues/18971),
4. [improved the performance of the window operator by using the sliding window](https://github.com/pingcap/tidb/issues/12967) which is a hard task,
5. helped other contributors and review [20 PRs](https://github.com/pingcap/tidb/pulls?q=is%3Apr+reviewed-by%3Ammyj+-author%3Ammyj+).

Thanks for his contribution! 🎊 🍾

### CODE REVIEW

**Comment by XuHuaiyu** [comment]
LGTM

**Comment by qw4990** [comment]
@XuHuaiyu @SunRunAway @zz-jason PTAL

**Review by SunRunAway — APPROVED** [review]
LGTM

**Comment by SunRunAway** [comment]
@winkyao @AndreMouche PTAL

**Review by winkyao — APPROVED** [review]
LGTM

**Comment by zz-jason** [comment]
LGTM

**Pull request merged**
