### PR TITLE
sig-exec: add bb7133 and bobotu as reviewers

### PR DESCRIPTION
**Pull request by qw4990**
bb7133: [100+ PRs](https://github.com/pingcap/tidb/pulls?page=1&q=is%3Apr+author%3Abb7133+is%3Aclosed) to TiDB
bobotu: [100+ PRs](https://github.com/pingcap/tidb/issues?q=is%3Apr+author%3Abobotu+is%3Aclosed) to TiDB

### CODE REVIEW

**Comment by qw4990** [comment]
PTAL @SunRunAway @winkyao @AndreMouche

**Review by SunRunAway — COMMENTED** [review]
LGTM

**Comment by zz-jason** [comment]
LGTM

**Comment by winkyao** [comment]
LGTM

**Review by winkyao — APPROVED** [review]

**Pull request merged**
