### PR TITLE
sig/planner: nominate rebelice as a committer of sig/planner

### PR DESCRIPTION
**Pull request by qw4990**
+ contribute [27 PRs](https://github.com/pingcap/tidb/issues?q=is%3Apr+author%3Arebelice+label%3Asig%2Fplanner+is%3Aclosed) to sig/planner
+ reviews [30+ PRs](https://github.com/pingcap/tidb/pulls?q=is%3Apr+is%3Aopen+reviewed-by%3Arebelice+label%3Acomponent%2Fstatistics) about the statistics component
+ implement the global statistics merge algorithm for partition tables
+ implement recording index usage information

### CODE REVIEW

**Comment by qw4990** [comment]
PTAL @zz-jason @winoros

**Comment by winoros** [comment]
+1

**Review by zz-jason — APPROVED** [review]
/lgtm

**Comment by qw4990** [comment]
@hi-rustin Could you please help us merge this PR?

**Pull request merged**
