### PR TITLE
sig-exec: promote b41sh to committer

### PR DESCRIPTION
**Pull request by qw4990**
Since @b41sh has contributed a lot to sig-exec, according to [sig-exec roles-and-organization-management.md#promotion](https://github.com/pingcap/community/blob/master/special-interest-groups/sig-exec/roles-and-organization-management.md#promotion), we would like to promote him to our new committer, and his detailed contribution is shown below:
1. contribute [40+ PRs](https://github.com/pingcap/tidb/pulls/b41sh) to the executor,
2. [using go template to vectorized 24+ builtin functions](https://github.com/pingcap/tidb/pull/12875) (a medium task),
3. support variable-setting hint [`SET_VAR`](https://github.com/pingcap/tidb/pull/20232) (a medium task),
4. implement [the framework of tracing `AggFun` memory](https://github.com/pingcap/tidb/pull/18257) and help other contributors add memory trace for [all aggregation functions](https://github.com/pingcap/tidb/issues/19369) (a hard task),
5. help other contributors and [review 25+ PRs](https://github.com/pingcap/tidb/pulls?q=is%3Apr+reviewed-by%3Ab41sh+-author%3Ab41sh+is%3Aopen).

Thanks for his contribution!! 😃 🎊

### CODE REVIEW

**Comment by qw4990** [comment]
PTAL @SunRunAway @winkyao @AndreMouche

**Comment by zz-jason** [comment]
LGTM

**Comment by winkyao** [comment]
LGTM, congratulation.

**Review by winkyao — APPROVED** [review]

**Comment by jackysp** [comment]
LGTM

**Comment by shenli** [comment]
LGTM

**Pull request merged**
