### PR TITLE
teams/bigdata: a vote for qidi1 as bigdata reviewer

### PR DESCRIPTION
**Pull request by shiyuhang0**
vote qidi1 as bigdata reviewer

### CODE REVIEW

**Review by humengyu2012 — APPROVED** [review]

**Review by sunxiaoguang — APPROVED** [review]
LGTM

**Comment by zhangyangyu** [comment]
Congrats @qidi1 !

**Comment by sunxiaoguang** [comment]
Congres  @qidi1!

**Comment by qidi1** [comment]
Thanks

**Pull request merged**
