### PR TITLE
promote Yisaer to reviewer

### PR DESCRIPTION
**Pull request by xhebox**
close https://github.com/pingcap/community/issues/421

### CODE REVIEW

**Review by Yisaer — APPROVED** [review]
LGTM

**Comment by hi-rustin** [comment]
/close 

Please follow the [new promotion process](https://docs.google.com/document/d/1OvlpU00W_LpTL09zB3gvDyQzHULz27kmNKH2O0seWCI/edit).

For example: https://github.com/pingcap/community/issues/414

**Pull request merged**
