### PR TITLE
sig-migrate: update membership

### PR DESCRIPTION
**Pull request by Ehco1996**
### GitHub Username
@Ehco1996

###  SIG you are requesting membership in
- sig-name: e.g. sig-migrate
- role: e.g. committer

### Requirements
- [x] I have reviewed the SIG promotion process guidelines(https://docs.google.com/document/d/1OvlpU00W_LpTL09zB3gvDyQzHULz27kmNKH2O0seWCI/edit?usp=sharing)
- [x] I am actively contributing to this SIG
- [x] I have two sponsors that meet the SIG roles-and-organization-management requirements
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @lichunzhu 
- @lance6716 

### List of contributions to the SIG’s project
- PRs reviewed / authored
  - [docs-dm](https://github.com/pingcap/docs-dm/pull/643)
  - [dm#1652](https://github.com/pingcap/dm/pull/1652)
  - [dm#1687](https://github.com/pingcap/dm/pull/1687)

- Issues responded to
  - [dm#1694](https://github.com/pingcap/dm/issues/1694)
  - [dm#1655](https://github.com/pingcap/dm/issues/1694)

- SIG projects I am involved with
  - dm
  - docs-dm
  - PingCAP-QE

### CODE REVIEW

**Comment by hi-rustin** [comment]
Please refer to this nomination process to make your nomination.

https://docs.google.com/document/d/1OvlpU00W_LpTL09zB3gvDyQzHULz27kmNKH2O0seWCI/edit

**Comment by Ehco1996** [comment]
@lichunzhu  @lance6716  please cc

**Comment by hi-rustin** [comment]
Please follow the process I provided to submit an issue and then submit a PR. thank you!

/close

**Comment by Ehco1996** [comment]
join rule is too deep to find...

leave a mark in case need to use it next time.

[sig-migrate-join-rule](https://github.com/pingcap/community/blob/3dc8e3d43db39b59bec36fa2c9033ed5740b72fd/special-interest-groups/sig-migrate/roles-and-organization-management.md)

**Pull request closed without merging**
