### PR TITLE
Promote liuzix to committer

### PR DESCRIPTION
**Pull request by liuzix**
I (@liuzix) now satisfy the requirements for being promoted to a commiter.

Requirements
- Have at least 30 PRs merged within one year (Yes, 34 PRs in TiCDC)
- Have reviewed at least 20 PRs within one year. (Yes, at least 25 in TiCDC)
- Nominated by at least 2 Committers or Maintainers. (@leoppro @amyangfei PTAL)

### CODE REVIEW

**Comment by leoppro** [comment]
LGTM

**Comment by liuzix** [comment]
@amyangfei @overvenus PTAL

**Comment by hi-rustin** [comment]
@zz-jason  Could you please `/merge` this PR？

**Comment by kennytm** [comment]
The SIG Tech leaders/co-leaders should be able to LGTM and merge these kinds of PRs. Are [these](https://github.com/pingcap/community/pull/372#issuecomment-756095194) the bot's bug?

**Comment by hi-rustin** [comment]
> The SIG Tech leaders/co-leaders should be able to LGTM and merge these kinds of PRs. Are [these](https://github.com/pingcap/community/pull/372#issuecomment-756095194) the bot's bug?

Please refer to https://docs.google.com/document/d/1gXQ5Qglgm2nhyU08ZVeluBM3PBKGgfN5zhgyalqhdyY. 
The robot divides PR permissions according to the documented permission design. If you have a problem with this, you can file an issue to discuss that part of the permission design.

**Comment by kennytm** [comment]
@hi-rustin #382.

**Pull request merged**
