### PR TITLE
teams/tidb: a vote for tisonkun as the committer

### PR DESCRIPTION
**Pull request by bb7133**
As stated in the title.

### CODE REVIEW

**Comment by bb7133** [comment]
Hi @pingcap/tidb-maintainers , PTAL

**Review by kennytm — APPROVED** [review]

**Review by breeswish — APPROVED** [review]

**Review by disksing — APPROVED** [review]

**Review by lonng — APPROVED** [review]

**Comment by disksing** [comment]
@bb7133 we can continue now.

**Comment by bb7133** [comment]
5 approves are collected, thank you! /cc @tisonkun

**Comment by tisonkun** [comment]
Thanks for your nomination! I'll keep contributing to TiDB :)

**Pull request merged**
