### PR TITLE
tiup: add srstack to maintainers

### PR DESCRIPTION
**Pull request by AstroProfundis**
Add @srstack to maintainers list, his our new colleague maintaining TiUP.

### CODE REVIEW

**Review by nexustar — APPROVED** [review]

**Comment by zhangyangyu** [comment]
-1. No offense to @srstack. But according to our company and community principle, roles should be earned by contribution, not by position. We can't assign our community roles to anyone just because he/she is a PingCAP employee going to maintain something. The role should be earned by contributions in work.

**Comment by AstroProfundis** [comment]
Be realistic, please.

When there is literally no active community member participating in the project, how can I adopt more people working on it by requiring "contribution"?

**Comment by zhangyangyu** [comment]
Simply giving roles and power wouldn't help right?

The truth is even with no roles, nothing would stop you from working on tiup right, following the conventional *issue -> PR -> review -> merge* procedure. If you think there is any obstacle in the workflow, then how would you expect there will be more contributors?

**Comment by AstroProfundis** [comment]
Nope, I need him to review and merge PRs, and the bot won't let him to do so.

**Comment by AstroProfundis** [comment]
I guess your next question is why I'd give a new comer permissions to approve and merge PRs, here's the fact.

With no more than 2 human resources (me and @nexustar, both half-timed) working on tiup, I have to review almost every single issue and PR, and even if the PR is reviewed by someone else, it's in most cases, if not all, me the only one having correctly permission to call `/merge` so the bot can do its job.

That's how it won't work to require "contributions" before granting permissions: I am the bottleneck.

**Comment by sunxiaoguang** [comment]
> let
No matter how many contributors are there. An open-source project always work the same way. Contributors earn authority by contributions but not position. As an engineer working on TiUP projects delicately, it takes very short time for him to make enough contributions to be nominated as reviewer and committer. Failing to do so effectively makes it not a real community project.

**Comment by AstroProfundis** [comment]
> Failing to do so effectively makes it not a real community project.

I'd say tiup is not. I never see any "real community project" having only 1 or 2 active developers and requiring bunch of rules of conducts.

I'd also be very appreciated if anyone could help making there more developers working on our repository.

**Comment by AstroProfundis** [comment]
I'm reopening this as @srstack already has more than a dozen of [PRs](https://github.com/pingcap/tiup/pulls?q=is%3Apr+is%3Amerged+author%3Asrstack) merged into TiUP's master branch, and some of them had released in our latest released.

**Comment by zhangyangyu** [comment]
okay, according to the governance model, first we need to hold for several days. And besides simply adding @srstack to the list, could you add a vote entry like other proposals? like https://github.com/pingcap/community/pull/619

**Comment by AstroProfundis** [comment]
That's a bit weird: every time someone made their vote the PR need to be updated?

**Comment by zhangyangyu** [comment]
> That's a bit weird: every time someone made their vote the PR need to be updated?

Update once at the final time I think. Honestly speaking the result part might be a little bit redundant, but plz at least add other content.

**Review by lucklove — APPROVED** [review]
LGTM

**Comment by AstroProfundis** [comment]
@zhangyangyu PTAL

**Comment by zhangyangyu** [comment]
I think the procedure conforms to the governance model. Feel free to merge.

**Comment by Mini256** [comment]
/unhold

cc: @zhangyangyu

**Pull request merged**
