### PR TITLE
teams/kubernetes: a vote for KanShiori as the committer

### PR DESCRIPTION
**Pull request by csuzhangxc**
As stated in the title.

### CODE REVIEW

**Comment by csuzhangxc** [comment]
Hi @pingcap/kubernetes-maintainers  , PTAL

**Comment by csuzhangxc** [comment]
+1

**Review by DanielZhangQD — APPROVED** [review]
LGTM

**Comment by DanielZhangQD** [comment]
+1

**Comment by zhangyangyu** [comment]
First congratulations to @KanShiori, the two @pingcap/kubernetes-maintainers has all approved the promotion. But one thing to note is that in the [governance model](https://github.com/pingcap/community/tree/master/teams#actions) we encourage all community members to participate in member votes. So every vote needs to keep hold for at least 6 days for any potential member to express themselves, both +1 and -1.

**Comment by sunxiaoguang** [comment]
A vote have be open for at least 6 days unless there is an objection or not enough votes. 
This PR was merged by mistake. We are going to revert it. @csuzhangxc please create a new PR and make sure the vote lasts long enough before it get merged. Thanks

**Comment by sunxiaoguang** [comment]
Let's see if it is possible to use bot to make sure vote process respect governance model @Mini256 @zhangyangyu

**Pull request merged**
