### PR TITLE
Promote coocoood and jackysp as committer for ddl sig

### PR DESCRIPTION
**Pull request by tangenta**
[coocood](https://github.com/coocood): [20+ PRs](https://github.com/pingcap/tidb/pulls?q=is%3Apr+author%3Acoocood) of TiDB DDL Component
[jackysp](https://github.com/jackysp): [20+ PRs](https://github.com/pingcap/tidb/pulls?q=is%3Apr+author%3Ajackysp+label%3Asig%2FDDL+is%3Aclosed) of TiDB DDL Component

### CODE REVIEW

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Comment by zz-jason** [comment]
LGTM

**Comment by hi-rustin** [comment]
/cc @pingcap/tidb-maintainer 

Needs `/merge`.

**Comment by hi-rustin** [comment]
/assign @pingcap/tidb-maintainer

Needs /merge.

**Comment by hi-rustin** [comment]
/assign @winkyao 

Needs `/merge`.

**Comment by jackysp** [comment]
> /assign @jackysp

I think it is not suitable for me to merge for myself.

**Comment by hi-rustin** [comment]
@winkyao ping~

**Pull request merged**
