### PR TITLE
fix: refine broken links

### PR DESCRIPTION
**Pull request by hi-rustin**
The site has been migrated.

### CODE REVIEW

**Comment by hi-rustin** [comment]
/hold

 The SIG in the URL must be capitalized, and this is being fixed.

**Review by Mini256 — COMMENTED** [review]
[The bigdata SIG's member list](https://github.com/pingcap/community/tree/821b8050e71ae00cc5a036bfd7f8955fa6b4f02b/special-interest-groups/sig-bigdata) is linked to the JSON file.  Maybe it also should be linked to the contributor website.

**Comment by hi-rustin** [comment]
> [The bigdata SIG's member list](https://github.com/pingcap/community/tree/821b8050e71ae00cc5a036bfd7f8955fa6b4f02b/special-interest-groups/sig-bigdata) is linked to the JSON file. Maybe it also should be linked to the contributor website.

The sig is not currently updated on the website, I will communicate with nick to add it.

**Pull request merged**
