### PR TITLE
*: update SIG-DDL member-list

### PR DESCRIPTION
**Pull request by zimulala**
The following is the number of PR that contributors have been merged:
xhebox merged 21 PRs
xiongjiwei merged 11 PRs
wangggong merged 10 PRs

### CODE REVIEW

**Comment by zimulala** [comment]
PTAL @tangenta @AilinKid

**Review by AilinKid — COMMENTED** [review]
LGTM

**Review by djshow832 — COMMENTED** [review]
LGTM

**Review by tangenta — COMMENTED** [review]
LGTM

**Review by AilinKid — APPROVED** [review]

**Comment by AndreMouche** [comment]
congratulations @wangggong @xiongjiwei @xhebox!

**Pull request merged**
