### PR TITLE
teams/migration: a vote for zhaoxinyu as the committer

### PR DESCRIPTION
**Pull request by amyangfei**
as title said

### CODE REVIEW

**Comment by amyangfei** [comment]
PTAL @lance6716 @overvenus @zhangyangyu , thanks!

**Review by lance6716 — APPROVED** [review]

**Review by overvenus — APPROVED** [review]
Congrats

**Comment by lance6716** [comment]
ping @zhangyangyu Do you need to manually update the committer list?

**Comment by zhangyangyu** [comment]
> ping @zhangyangyu Do you need to manually update the committer list?

Done

**Pull request merged**
