### PR TITLE
teams/tidb: a vote for aytrack as the reviewer

### PR DESCRIPTION
**Pull request by bb7133**
As stated in the title.

### CODE REVIEW

**Comment by tisonkun** [comment]
/cc @pingcap/tidb-maintainers 

With an offline discussion with @bb7133 , we're still exploring the principle to accept contribution beyond code. It's better to listen to opinions from our maintainers.

I'll prepare a draft of committer principle later.

**Comment by zhangyangyu** [comment]
ping @pingcap/tidb-maintainers

**Comment by zhangyangyu** [comment]
https://github.com/pingcap/community/pull/601

**Pull request merged**
