### PR TITLE
update membership of tiup

### PR DESCRIPTION
**Pull request by AstroProfundis**
- Add @nexustar to committers list, he's our new colleague maintaining TiUP.
- Also adjusting member roles

### CODE REVIEW

**Comment by tisonkun** [comment]
Hi @AstroProfundis ! I think you should also be interested in this PR https://github.com/pingcap/community/pull/522/files#diff-c789528d17f96819c1261cb732cc1f735a91368ac1f5580032f735a6fbdb34e5 .

**Comment by tisonkun** [comment]
Also, I suggest you describe what @nexustar did for the community, and invite @nexustar to speak out his plan on maintaining the repository. We'd better avoid violate rules setting by ourselves saying contributor will earn authority by their contribution. Join PingCAP is _not_ a contribution to the community.

**Comment by AstroProfundis** [comment]
At present I'm the only active maintainer working on TiUP, @lucklove is no longer spending much time on it. I need @nexustar to review and merge my PR.

**Comment by tisonkun** [comment]
@AstroProfundis https://github.com/pingcap/community/pull/522/files#diff-9f53dd5e915af9c2f1fa65c5523c8a6dfac69b84dc14c34e19ae781627d48e58

**Review by tisonkun — APPROVED** [review]
Thanks for updating the info. Merging...

**Pull request merged**
