### PR TITLE
teams/tidb: a vote for 'TonsnakeLin' as the reviewer

### PR DESCRIPTION
**Pull request by you06**
Signed-off-by: you06 <you1474600@gmail.com>

See the [vote doc](https://github.com/you06/community/blob/TonsnakeLin-reviewer/votes/0716-TonsnakeLin-as-tidb-reviewer.md).

### CODE REVIEW

**Comment by you06** [comment]
@cfzjywxk @sticnarf @ekexium PTAL
cc @TonsnakeLin

**Review by ekexium — APPROVED** [review]
LGTM. I was going to propose the same thing.

I'd also like to call a vote for @you06 and myself for a promotion to committers. What do you think?

**Review by disksing — APPROVED** [review]

**Comment by disksing** [comment]
@zhangyangyu any particular reason to hold this?

**Comment by zhangyangyu** [comment]
> @zhangyangyu any particular reason to hold this?

hold when the issue is opened to prevent merge too quickly. Promote a reviewer requires 3 days at least.

**Comment by disksing** [comment]
> > @zhangyangyu any particular reason to hold this?
> 
> @disksing hold when the issue is opened to prevent merge too quickly. Promote a reviewer requires 3 days at least.

thanks. got it.

**Comment by you06** [comment]
@zhangyangyu it has been more than 3 days since 2 approves, can we merge this PR?

**Pull request merged**
