### PR TITLE
teams/tidb: a vote for hawkingrei as reviewer

### PR DESCRIPTION
**Pull request by zimulala**
As stated in the title.

### CODE REVIEW

**Review by wjhuang2016 — COMMENTED** [review]
+1

**Comment by tangenta** [comment]
LGTM

**Comment by bb7133** [comment]
+1

**Review by sunxiaoguang — APPROVED** [review]

**Comment by sunxiaoguang** [comment]
Thanks for your contribution @hawkingrei. Congrats.

**Pull request merged**
