### PR TITLE
README: update links

### PR DESCRIPTION
**Pull request by UtopiaScript**
Update the relative path to URL to ensure normal redirection of community website

### CODE REVIEW

**Comment by UtopiaScript** [comment]
@tiancaiamao The new DevGroup Website will show each sig README.md as sig detail page, http://developer.tidb.io/SIG/sql-infra  the relative path is 404 

image
image

**Comment by XuHuaiyu** [comment]
LGTM

**Comment by hi-rustin** [comment]
> LGTM

Please use /lgtm command.

**Pull request merged**
