### PR TITLE
sig-docs: rm links to dbaas-docs

### PR DESCRIPTION
**Pull request by ran-huang**
Signed-off-by: Ran <huangran@pingcap.com>

### CODE REVIEW

**Comment by hi-rustin** [comment]
@lilin90 @yikeke

Did you guys get kicked out of pingcap org yesterday because of 2FA restrictions?

**Review by lilin90 — COMMENTED** [review]
It seems that we'd better also remove line 18 because it's not a public repo now that contributors can contribute. 🤔
- [TiDB Cloud](https://pingcap.com/products/tidbcloud)

**Comment by ran-huang** [comment]
> It seems that we'd better also remove line 18 because it's not a public repo now that contributors can contribute. 🤔
> 
> * [TiDB Cloud](https://pingcap.com/products/tidbcloud)

Done. PTAL

**Pull request merged**
