### PR TITLE
teams/docs: a vote for ngaut as the reviewer

### PR DESCRIPTION
**Pull request by lilin90**
As stated in the title.

### CODE REVIEW

**Comment by lilin90** [comment]
Hi @pingcap/docs-maintainers, PTAL.

**Review by qiancai — APPROVED** [review]

**Comment by qiancai** [comment]
LGTM

**Review by TomShawn — APPROVED** [review]
LGTM

**Review by hfxsd — APPROVED** [review]
LGTM

**Review by disksing — APPROVED** [review]

**Comment by lilin90** [comment]
This voting has met the requirement and I'm going to merge this PR. If you have any concerns, please let me know. Thanks!

**Pull request merged**
