### PR TITLE
sig-docs: promote CharLotteiu to committer; promote Joyinqin to reviewer

### PR DESCRIPTION
**Pull request by ran-huang**
According to [Be promoted to Committer](https://github.com/pingcap/community/blob/master/special-interest-groups/sig-docs/roles-and-organization-management.md#be-promoted-to-committer), we would like to promote @CharLotteiu to a new committer of Docs SIG. Her detailed contribution is shown below:
- Have reviewed 89 PRs in docs-related repos
- Improve docs maintenance efficiency:
    - Add conflict mark check in 4 docs repos (https://github.com/pingcap/docs/pull/4026, https://github.com/pingcap/docs-cn/pull/4696, https://github.com/pingcap/docs-dm/pull/438, https://github.com/pingcap/docs-tidb-operator/pull/786)
    - Create [a Chrome extension](https://chrome.google.com/webstore/detail/quickswitch/knjplddkmcgipbanhljlbkphpmkhgkfd?hl=zh-CN&authuser=0) to enable quick switch between Chinese and English documentation
- Add Vale as a language linter in docs-related repos
- Make GitHub tutorial videos for beginner-level contributors

---

According to [Be promoted to Reviewer](https://github.com/pingcap/community/blob/master/special-interest-groups/sig-docs/roles-and-organization-management.md#be-promoted-to-reviewer), we would like to promote @Joyinqin to a new reviewer of Docs SIG. Her detailed contribution is shown below:
- Have merged 171 PRs in docs-related repos
- Improve document image quality (https://github.com/pingcap/docs-cn/pull/4672, https://github.com/pingcap/docs-cn/pull/4932, https://github.com/pingcap/docs/pull/4143, https://github.com/pingcap/docs/pull/4208, https://github.com/pingcap/docs-dm/pull/484)
- Update or remove third-party logos in document to resolve legal concerns (https://github.com/pingcap/docs/pull/4291, https://github.com/pingcap/docs-cn/pull/5101, https://github.com/pingcap/docs-cn/pull/5011, https://github.com/pingcap/docs-cn/pull/5101, https://github.com/pingcap/docs-cn/pull/5011, etc)

### CODE REVIEW

**Review by yikeke — APPROVED** [review]
LGTM

**Review by lilin90 — APPROVED** [review]
LGTM

**Comment by coocood** [comment]
LGTM

**Comment by hi-rustin** [comment]
> LGTM

Please use `/LGTM`.

**Comment by hi-rustin** [comment]
@coocood @zz-jason  Could you please `/merge` it if you think it can be merge?

**Pull request merged**
