### PR TITLE
sig-exec: update the member list

### PR DESCRIPTION
**Pull request by qw4990**
Yisaer: [20+ PRs](https://github.com/pingcap/tidb/pulls?q=is%3Apr+author%3AYisaer+label%3Asig%2Fexecution+is%3Aopen) of TiDB Executor Component

### CODE REVIEW

**Comment by qw4990** [comment]
PTAL @XuHuaiyu @SunRunAway @AndreMouche @Yisaer

**Review by SunRunAway — COMMENTED** [review]
LGTM

**Comment by XuHuaiyu** [comment]
LGTM

**Review by XuHuaiyu — APPROVED** [review]

**Review by Yisaer — COMMENTED** [review]
LGTM

**Review by AndreMouche — APPROVED** [review]

**Pull request merged**
