### PR TITLE
teams/tidb: a vote for dveeden as the reviewer(again)

### PR DESCRIPTION
**Pull request by bb7133**
As stated in the title.

### CODE REVIEW

**Comment by bb7133** [comment]
hi @pingcap/tidb-maintainers , PTAL.

The only possible concern from me is that most of Daniel's work is related(or limited) to authentication and security. But I think his work in those areas is impressive enough.

Please let me know if you have any concerns/suggestions.

**Comment by bb7133** [comment]
>  The vote will be open for at least 3 days unless there is an objection or not enough votes.

The PR will be held for 3 days.

**Review by jackysp — APPROVED** [review]

**Review by disksing — APPROVED** [review]

**Review by tiancaiamao — APPROVED** [review]

**Comment by bb7133** [comment]
Hi @pingcap/tidb-maintainers , 4 binding votes have been collected. I will merge this PR today.

**Review by lonng — APPROVED** [review]

**Comment by bb7133** [comment]
Close this PR by merging it.

**Pull request merged**
