### PR TITLE
teams/tidb: a vote for hawkingrei as the TiDB commiter

### PR DESCRIPTION
**Pull request by bb7133**
As stated in the title, thanks.

### CODE REVIEW

**Review by tiancaiamao — APPROVED** [review]

**Review by zimulala — APPROVED** [review]
LGTM

**Comment by tiancaiamao** [comment]
@bb7133 I guess we can merge it now~

**Comment by hawkingrei** [comment]
@bb7133 Please fix the conflict.

**Comment by bb7133** [comment]
@pingcap/tidb-maintainers This PR will be merged since enough votes are collected.

**Pull request merged**
