### PR TITLE
promote morgo to committer

### PR DESCRIPTION
**Pull request by tangenta**
@morgo now satisfies the requirements for being promoted to a committer.

Requirements

- [x] Have at least [20 PRs](https://github.com/pingcap/tidb/pulls/morgo) merged.
- [x] Have reviewed at [least 10 PRs](https://github.com/pingcap/tidb/pulls?q=is%3Apr+reviewed-by%3Amorgo).
- [x] Nominated by at least 2 Committers or Maintainers.

### CODE REVIEW

**Review by djshow832 — COMMENTED** [review]
LGTM

**Comment by bb7133** [comment]
LGTM

**Comment by bb7133** [comment]
PTAL @hi-rustin @sykp241095

**Comment by hi-rustin** [comment]
> PTAL @hi-rustin @sykp241095

Please use `/lgtm` or directly approve the PR.

**Comment by tiancaiamao** [comment]
LGTM

**Comment by hi-rustin** [comment]
> LGTM

Please use `/LGTM`.

**Pull request merged**
