### PR TITLE
sig-k8s: promote DanielZhangQD (zhanghailong@pingcap.com) to the leader

### PR DESCRIPTION
**Pull request by cofyc**

### CODE REVIEW

**Review by lonng — APPROVED** [review]
@cofyc Prefer to move you to the `Co-Leaders` section instead of `Committers`.

**Review by Yisaer — APPROVED** [review]
LGTM

**Comment by cofyc** [comment]
> @cofyc Prefer to move you to the `Co-Leaders` section instead of `Committers`.

I'm afraid I don't have enough time.

**Comment by cofyc** [comment]
cc @DanielZhangQD @AndreMouche

**Pull request merged**
