### PR TITLE
Add Wallace to committers

### PR DESCRIPTION
**Pull request by Little-Wallace**
Signed-off-by: Little-Wallace <bupt2013211450@gmail.com>

### CODE REVIEW

**Comment by kennytm** [comment]
We have checked this proposal in the [regular SIG-Migrate meeting](https://app.slack.com/client/TH91JCS4W/C013HGZMBAR/thread/C01H4GW3WR5-1609817991.024900). As @Little-Wallace is an experienced contributor to TiKV, we believe this has enough evident he is capable of being a committer in SIG-Migrate as well. Thus we will approve this PR as an exceptional case.

/lgtm

**Comment by hi-rustin** [comment]
> /approve

`/merge`

**Pull request merged**
